### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by AJJLagerweij** [PhilippC/kp2a_accservice_autofill#19]
Hi everyone,
Just to simplify it for dimwits like me.
On what browsers is it working (a list), and for what browsers do simple changes suffice such as those for brave #11 ?
Regards,
Bram

**Comment by JetUni** [comment]
It seems like it only works in Chrome. I just tried Firefox and got nothing, and in edge it detects the form, but not the url.

**Comment by AJJLagerweij** [comment]
Thanks, that is clear.
