### ISSUE TITLE
Does not install on Android 4.4.2

### ISSUE THREAD

**Issue by thenlich** [PhilippC/kp2a_accservice_autofill#2]
Installation on Lenovo A5500-F aborts with "parse error – there is an error parsing the package" even after deleting and downloading apk again. (Device not rooted)

**Comment by madagit** [comment]
Same here: Installation on rooted Samsung Galaxy S3 Neo ( GT- i9301i ) with Android 4.4.2
 aborts with "parse error – there is an error parsing the package" even after deleting and downloading apk again. Tried again a few times: no result, same parse error.

**Comment by PhilippC** [comment]
this app only works Android 5.0 feature and thus has a minSdkVersion=21 setting. It cannot work on Android 4 - sorry.

**Comment by thenlich** [comment]
The minimum required software versions should be in the README in order to make this clear.
