### ISSUE TITLE
Brave Browser is not supported

### ISSUE THREAD

**Issue by JulesLecuir** [PhilippC/kp2a_accservice_autofill#29]
Hi,

I tried to used Keepass2Android with Brave Browser which is a Chromium based browser, but it doesn't work. The notification appears but the app is considered as an application and not as a web browser (Google Chrome seems to work on Android, so why not Brave Browser? :) )

**Comment by sebaeee** [comment]
Same for me, if you try from context popup (not from nitification) works fone, but if you tap in notification autofill, brave or firefox not show the url but only the title of the application

**Comment by Jonny-T-cyber** [comment]
Same for me...
No fix?

**Comment by PhilippC** [comment]
please request proper Android Autofill support at the Brave support page. KP2A works if Autofill is implemented by the target app.
