### ISSUE TITLE
Firefox 57

### ISSUE THREAD

**Issue by mr-monk** [PhilippC/kp2a_accservice_autofill#3]
Hy. 

Is there any way to get it working with Firefox 57?

Cherrs

**Comment by PhilippC** [comment]
unfortunately not. Firefox does not make its controls accessible to the accessibility framework.

**Comment by nils-werner** [comment]
This recently seems to have changed. I am seeing autofill dialogs when I see password prompts on Firefox 64.0.1 and Android 9.0 Pie.

Unfortunately keepass is searching for the URL `androidapp://org.mozilla.firefox`
