### ISSUE TITLE
kp2a.plugin.AutoFill-1.02.apk VirusTotal positive result

### ISSUE THREAD

**Issue by gretraholisi** [PhilippC/kp2a_accservice_autofill#32]
As of 2020-09-04 09:36 UTC, one of the AV engines used by VirusTotal is indicating that [kp2a.plugin.AutoFill-1.02.apk](https://github.com/PhilippC/kp2a_accservice_autofill/releases/download/v1.02/kp2a.plugin.AutoFill-1.02.apk) is a [Trojan/Linux.Generic](https://www.virustotal.com/gui/file/d7a9ae29011b596fce5c1331c386f4563538b653e3656aa60964bf2f26dea4cc)

**Comment by PhilippC** [comment]
that's not correct. Just because some automatic tool has a hard time to understand Xamarin APKs is not a bug here.
