### ISSUE TITLE
Plugin crashes often, at random times

### ISSUE THREAD

**Issue by lupalby** [PhilippC/kp2a_accservice_autofill#4]
While browsing on Instagram I often get the popup that this plugin stopped working. No form or login page was displayed, just scrolling through the posts.
Galaxy S8, Android Oreo

**Comment by popy2k14** [comment]
Same here on lg g4 nougat v29 when browsing different pages in Chrome. Also when no login form is on the page. 

Any chance to get a fix?

**Comment by lupalby** [comment]
I started getting random crashes on chrome too. It doesn't seem to be related to a particular website or the presence of forms.

**Comment by popy2k14** [comment]
@PhilippC : Seems there is a workaround to not recurse a child if its the same as the parent, see here: https://bugs.chromium.org/p/chromium/issues/detail?id=808751#c11

Can you please implement this workaround?

thx
pOpY

**Comment by gdlin** [comment]
U have the same bug, it's driving me crazy. It seems to crash when I'm using waze. Please tell us if you need a logcat or if there's anything we can do to help.

**Comment by vertigo220** [comment]
I'm also having this issue. Just installed it an hour or so ago and, with only minimal use of the phone since, it's crashed twice. The last time I was using the Play Store, though it might have happened when switching to or back from the Gmail app. Don't remember what I was doing the first time, but pretty sure it was something similar, and I wasn't using Chrome or Instagram. This is on a Moto Z Play running 7.1.1.

**Comment by PhilippC** [comment]
@popy2k14 I tried implementing the workaround but without effect, I still got crashes. This needs further investigation.

**Comment by popy2k14** [comment]
@PhilippC: thx for the update. hope you are finding an suitable workaround.

**Comment by kifujin** [comment]
As a head's up, another issue was created on the [main projects issue page](/PhilippC/keepass2android/issues/281).

**Comment by lupalby** [comment]
I started using the plug-in again after several months and now it seems I don't get any more crashes. Not sure if Android fixed something or if Keepass did, but it has been running smoothly so far.
The issue mentioned by @kifujin also got closed because the problem seems fixed.

**Comment by vertigo220** [comment]
I also haven't had any crashes in a while. Strange, but hey, it works!
