### ISSUE TITLE
is there a way to use this without disabling device encryption?

### ISSUE THREAD

**Issue by XIncognito10** [PhilippC/kp2a_accservice_autofill#6]
Update: It turns out, even though enabling the service will bring up a message saying device encryption will be deactivated, you can still go back to your screen lock and reenter your pin/password again to reactivate the device encryption. Heres a link with further info https://forum.xda-developers.com/nexus-6p/help/warning-how-accessibility-services-t3265174. Im closing the issue but ill leave this message here for posterity

**Comment by nils-werner** [comment]
I am using this on my OnePlus 5T with device encryption enabled, on both Nougat and Oreo.
